name: designthinking
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+4
  path_provider: ^2.1.2
  path: ^1.9.0
  image: ^3.0.0
  image_picker: ^1.1.2
  sensors_plus: ^5.0.1
  vibration: ^1.7.4
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  location: ^5.0.3
  geocoding: ^3.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  local_auth: ^2.1.8
  app_settings: ^5.1.1
  haversine_distance: ^1.2.1
  permission_handler: ^11.0.1
  audioplayers: ^5.2.1
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  firebase_core: ^3.4.0  # Use the latest version
  cloud_firestore: ^5.4.1
  google_maps_flutter: ^2.9.0  # Added for Google Maps

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets here
  assets:
    - assets/sounds/alert.mp3

  # To add custom fonts to your application, uncomment and configure:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700