// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0H9TLrzdgji1-sg8s38hq655cxsrGL8Q',
    appId: '1:970461684556:web:2882c201558efbec9fa5e9',
    messagingSenderId: '970461684556',
    projectId: 'bike-safety-4edb0',
    authDomain: 'bike-safety-4edb0.firebaseapp.com',
    storageBucket: 'bike-safety-4edb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvBOWqSVhWD67HW5iVnC9y7GaN0vIFf4',
    appId: '1:970461684556:android:45239e1c0ec038779fa5e9',
    messagingSenderId: '970461684556',
    projectId: 'bike-safety-4edb0',
    storageBucket: 'bike-safety-4edb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX4EEjFvYhRaS8_2Z0qICyZMSrULjfjC0',
    appId: '1:970461684556:ios:1d85d808c37d5be59fa5e9',
    messagingSenderId: '970461684556',
    projectId: 'bike-safety-4edb0',
    storageBucket: 'bike-safety-4edb0.firebasestorage.app',
    iosBundleId: 'com.example.designthinking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX4EEjFvYhRaS8_2Z0qICyZMSrULjfjC0',
    appId: '1:970461684556:ios:1d85d808c37d5be59fa5e9',
    messagingSenderId: '970461684556',
    projectId: 'bike-safety-4edb0',
    storageBucket: 'bike-safety-4edb0.firebasestorage.app',
    iosBundleId: 'com.example.designthinking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0H9TLrzdgji1-sg8s38hq655cxsrGL8Q',
    appId: '1:970461684556:web:05fadbfe0ae3cabf9fa5e9',
    messagingSenderId: '970461684556',
    projectId: 'bike-safety-4edb0',
    authDomain: 'bike-safety-4edb0.firebaseapp.com',
    storageBucket: 'bike-safety-4edb0.firebasestorage.app',
  );
}
